<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent Model representing an RCA insurance quotation generated by an external provider.
 * It stores pricing details, insurer identifiers, and links back to the audit trail
 * of the request.
 */
class RcaOffer extends Model
{
    /**
     * Disable mass assignment protection by specifying an empty guarded array.
     * Allows bulk creation of quotation attributes parsed directly
     * from external provider responses.
     */
    protected $guarded = [];

    /**
     * Get the audit log entry associated with the respective quotation.
     * Defines an inverse one-to-many relationship using 'audit_log_id'
     * foreign key.
     */
    public function auditLog()
    {
        return $this->belongsTo(RcaAuditLog::class, 'audit_log_id');
    }
}
